stages:
- test

language: node_js
node_js:
- '10'

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then script/apt-get-install-deps; fi
- script/install-shadow-node
- yarn

script:
- yarn build
- yarn test

jobs:
  include:
  - stage: test
    os: linux
    dist: trusty
